interactive:
	condor_submit -interactive jobs/interactive-cpu.job
interactive-cpu:
	condor_submit -interactive jobs/interactive-cpu.job
interactive-gpu:
	condor_submit -interactive jobs/interactive-gpu.job
interactive-ros:
	condor_submit -interactive jobs/interactive-singularity.job
