green_list:
  - asahi
  - bandai
  - chokai
  - daisen
  - ena
  - fuji
  - goryu
  - hoo
  - iwaki
  - jonen
  - amager
  - bornholm
  - christianso
  - drejo
  - egholm
  - funen
  - gavno
  - hirsholm
  - ilumo
  - kalvo
  - hal
  - avocado
  - banana
  - cherry
  - durian
  - andromeda
  - vega
  - wasat
  - yildun
  - nickeline
  - opal
  - pyrite
  - quartz
  - realgar
  - spinal
  - topaz
  - ulexite
  - vauxite
  - askoy
  - molder
  - integra
  - deneve
  - driefonteinen
  - goudenband
  - hommage
  - bellegems