output_path: cube_world
mode: dag_train_evaluate
job_configs:
  - command: python3 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 8
    gpus: 1
    cpu_mem_gb: 10
    disk_mem_gb: 52
    wall_time_s: 60 * 60 * 10
    nice: true
    gpu_mem_mb: 1900
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
  - command: python3 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 11
    gpus: 1
    cpu_mem_gb: 25
    disk_mem_gb: 52
    wall_time_s: 60 * 60
    nice: true
    gpu_mem_mb: 1900
    use_singularity: true
    check_if_ros_already_in_use: true
    save_locally: true
    extra_requirements: ( Mips >= 26000 )
number_of_jobs:
  - 3
  - 3
base_config_files:
  - src/scripts/config/il_train_cube_world.yml
  - src/scripts/config/il_evaluate_interactive_cube_world.yml