output_path: adversarial-dummy-tracking
mode: default
wait_time_between_jobs_sec: 0.1
number_of_jobs:  # indicates number of seeds per parameter value
  - 10
base_config_files:
  - src/scripts/config/dummy_adversarial_ppo.yml
job_configs:
  - command: python3 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 5
    gpus: 0
    cpu_mem_gb: 5
    disk_mem_gb: 52
    wall_time_s: 10 * 3600
    nice: true
    use_singularity: false
    check_if_ros_already_in_use: false
    save_locally: true
    save_before_wall_time: true
