output_path: cube_world
mode: data_collection
job_configs:
  - command: python3 src/scripts/experiment.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 11
    gpus: 1
    cpu_mem_gb: 25
    disk_mem_gb: 52
    wall_time_s: 60 * 60
    nice: true
    priority: -10
    use_singularity: true
    check_if_ros_already_in_use: true
    save_locally: true
    extra_requirements: ( Mips >= 26000 )
number_of_jobs:
  - 5
base_config_files:
  - src/scripts/config/il_data_collection_cube_world.yml