output_path: cube_world
mode: default
job_configs:
  - command: python3 src/scripts/data_cleaning.py
    codebase_dir: /users/visics/kkelchte/code/imitation-learning-codebase
    cpus: 2
    gpus: 0
    cpu_mem_gb: 18
    disk_mem_gb: 52
    wall_time_s: 10 * 60
    nice: true
    use_singularity: false
    check_if_ros_already_in_use: False
    save_locally: False
number_of_jobs:
  - 1
base_config_files:
  - src/scripts/config/il_data_cleaning_cube_world.yml