world_name: debug_turtle
max_duration: -1
delay_evaluation: 1.
goal:
  x:
    min: 1.7
    max: 2.2
  y:
    min: 1.7
    max: 2.2
  z:
    min: -1
    max: 1.5
waypoints:
  - [0, 1]
  - [1, 1]
  - [1, 2]
  - [2, 2]
waypoint_reached_distance: 0.1
reward:
  on_collision:
    termination: 'Failure'
    weights:
      constant: -100
  goal_reached:
    termination: 'Success'
    weights:
      constant: 100
  step:
    termination: 'NotDone'
    weights:
      constant: -1