world_name: hexagon
max_duration: 60
delay_evaluation: 1.0
waypoints:
  - [ 1, 0 ]
  - [ 1.7, 1 ]
  - [ 3.3, 1 ]
  - [ 4, 0 ]
  - [ 3.3, -1 ]
  - [ 1.7, -1 ]
goal:
  x:
    min: 0.5
    max: 1.5
  y:
    min: -1.0
    max: -0.2
  z:
    min: .5
    max: 1.5
waypoint_reached_distance: 0.25
express_waypoints_locally: True