rate_fps: 60
mapping:
  Unknown:
    command: '/actor/joystick/cmd_vel'
  Terminated:
    command: '/actor/joystick/cmd_vel'
  Running:
    command: '/ros_python_interface/cmd_vel'
  TakenOver:
    command: '/actor/joystick/cmd_vel'
  DriveBack: {}