rate_fps: 60
mapping:
  Unknown:
    command: '/actor/keyboard/cmd_vel'
  Terminated:
    command: '/actor/keyboard/cmd_vel'
  Running:
    command: '/actor/keyboard/cmd_vel'
  TakenOver:
    command: '/actor/keyboard/cmd_vel'
  DriveBack:
    command: '/actor/keyboard/cmd_vel'