output_path: test_joystick_flight
number_of_epochs: 1
episode_runner_config:
  number_of_episodes: 20
environment_config:
  factory_key: ROS
  max_number_of_steps: -1
  ros_config:
    observation: camera
    action_topic: /actor/ros_expert/cmd_vel
    visible_xterm: true
    step_rate_fps: 30
    max_update_wait_period_s: 10
    ros_launch_config:
      random_seed: 123
      robot_name: tello_real
      robot_display: true
      fsm_mode: TakeOverRun
      fsm: true
      control_mapping: true
      waypoint_indicator: false
      control_mapping_config: joystick
      world_name: default
    actor_configs:
#      - name: keyboard
#        file: src/sim/ros/config/actor/keyboard_bebop_real.yml
      - name: joystick
        file: src/sim/ros/config/actor/joystick_tello_real.yml
data_saver_config:
  store_hdf5: false
  separate_raw_data_runs: true
  saving_directory_tag: joystick