output_path: /home/klaas/code/imitation-learning-codebase/experimental_data/adam_lr000001/models/seed_5100
number_of_epochs: 1
episode_runner_config:
  number_of_episodes: 10
load_checkpoint_dir: /home/klaas/code/imitation-learning-codebase/experimental_data/adam_lr000001/models/seed_5100
architecture_config:
  architecture: dronet_sidetuned
  device: cpu
environment_config:
  factory_key: ROS
  max_number_of_steps: -1
  ros_config:
    observation: camera
    visible_xterm: true
    step_rate_fps: 100
    ros_launch_config:
      random_seed: 123
      robot_name: bebop_real
      robot_display: true
      fsm_mode: TakeOverRun
      fsm: true
      control_mapping: true
      waypoint_indicator: false
      control_mapping_config: takeover_joystick
      world_name: empty
      x_pos: 0.0
      y_pos: 0.0
      z_pos: 1.0
      yaw_or: 1.57
      gazebo: false
    actor_configs:
        #- name: keyboard
        #  file: src/sim/ros/config/actor/keyboard_bebop_real.yml
        - name: joystick
          file: src/sim/ros/config/actor/joystick_bebop_real.yml
data_saver_config:
  store_hdf5: false
  separate_raw_data_runs: true
  saving_directory_tag: evaluate