output_path: line_world/dronet_finetuned/real_sim_noisy_augmented
number_of_epochs: 31
episode_runner_config:
  number_of_episodes: -1
save_checkpoint_every_n: 10
load_checkpoint_dir: dronet
architecture_config:
  architecture: dronet
  initialisation_type: xavier
  random_seed: 123
  device: cpu
  dropout: default
  dtype: default
  log_std: default
  finetune: true
trainer_config:
  optimizer: SGD
  learning_rate: 0.0001
  factory_key: BASE
  data_loader_config:
    hdf5_files:
    - line_world_data/sim/line_world_sim_dronet_noise_augmented_wp.hdf5
    - line_world_data/real/train.hdf5
    - line_world_data/sim/line_world_sim_dronet_noise_augmented_manual.hdf5
    input_size: [1, 200, 200]
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: L1Loss
  device: cuda
evaluator_config:
  data_loader_config:
    input_size: [1, 200, 200]
    hdf5_files:
    - line_world_data/real/validation.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cpu
  evaluate_extensive: true
tensorboard: true
