output_path: test_train_smooth_line
number_of_epochs: 200
episode_runner_config:
  number_of_episodes: -1
save_checkpoint_every_n: 10
architecture_config:
  architecture: bc_deeply_supervised_auto_encoder
  initialisation_type: xavier
  random_seed: 4
  device: cuda
  dropout: default
  batch_normalisation: default
  vae: false
  dtype: default
  log_std: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.001
  factory_key: DS
  weight_decay: 0.0
  gradient_clip_norm: -1
  store_feature_maps_on_tensorboard: True
  data_loader_config:
    loop_over_hdf5_files: true
    hdf5_files:
      - /gluster/visics/kkelchte/hdf5_files/line_world/mixed_smoothed_label/1_200/train_0.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/mixed_smoothed_label/1_200/train_1.hdf5
    random_seed: 123
    balance_over_actions: false
    batch_size: 32
  criterion: WeightedBinaryCrossEntropyLoss
  criterion_args_str: 'beta=0.9'
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
      -  /gluster/visics/kkelchte/hdf5_files/line_world/mixed_smoothed_label/1_200/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 32
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
tester_config:
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
      -  /gluster/visics/kkelchte/hdf5_files/line_world/real/1_200_200/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 32
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
  evaluate_extensive: true
tensorboard: true
