output_path: test_discriminator
number_of_epochs: 600
episode_runner_config:
  number_of_episodes: -1
save_checkpoint_every_n: 10
architecture_config:
  architecture: auto_encoder_deeply_supervised_confidence
  initialisation_type: xavier
  random_seed: 4
  device: cuda
  dropout: default
  batch_normalisation: default
  vae: false
  dtype: default
trainer_config:
  optimizer: Adam
  learning_rate: 0.001
  critic_learning_rate: 0.001
  epsilon: 0.2
  factory_key: DeepSupervisionConfidence
  weight_decay: 0.0
  data_loader_config:
    batch_size: 10
    hdf5_files:
#      - hdf5_files/1_200/sim/tiny_dummy.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_0.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_1.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_10.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_11.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_12.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_13.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_14.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_15.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_16.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_17.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_18.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_19.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_20.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_21.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_22.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_23.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_2.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_3.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_4.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_5.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_6.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_7.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_8.hdf5
      - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/train_9.hdf5
    loop_over_hdf5_files: true
    random_seed: 123
    balance_over_actions: false
  criterion: WeightedBinaryCrossEntropyLoss
  criterion_args_str: 'beta=0.9'
  device: cuda
  store_output_on_tensorboard: true
evaluator_config:
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
#      - hdf5_files/1_200/sim/tiny_dummy.hdf5
      - - /gluster/visics/kkelchte/hdf5_files/line_world/motion_blurred_lines/1_200/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 20
  criterion: WeightedBinaryCrossEntropyLoss
  criterion_args_str: 'beta=0.9'
  device: cuda
  store_output_on_tensorboard: true
tester_config:
  data_loader_config:
    loop_over_hdf5_files: false
    hdf5_files:
#      - hdf5_files/1_200/sim/tiny_dummy.hdf5
      -  /gluster/visics/kkelchte/hdf5_files/line_world/real/1_200_200_shuffled/validation_0.hdf5
    random_seed: 32
    balance_over_actions: false
    batch_size: 20
  criterion: MSELoss
  device: cuda
  store_output_on_tensorboard: true
  evaluate_extensive: false
tensorboard: true
