output_path: cube_world
number_of_epochs: 60
episode_runner_config:
  number_of_episodes: -1
save_checkpoint_every_n: 10
architecture_config:
  architecture: tiny_128_rgb_6c
  initialisation_type: xavier
  random_seed: 123
  device: cpu
  dropout: default
  dtype: default
  log_std: default
trainer_config:
  optimizer: SGD
  weight_decay: 0.0001
  learning_rate: 0.01
  factory_key: BASE
  data_loader_config:
    hdf5_files: [cube_world/train_0.hdf5]
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cuda
evaluator_config:
  data_loader_config:
    hdf5_files: [cube_world/validation_0.hdf5]
    random_seed: 123
    balance_over_actions: false
    batch_size: 64
  criterion: MSELoss
  device: cpu
tensorboard: true