output_path: line_world
number_of_epochs: 1
episode_runner_config:
  number_of_episodes: 1
load_checkpoint_dir: line_segmentation_network
architecture_config:
  architecture: auto_encoder_deeply_supervised_with_discriminator
  device: cuda
environment_config:
  factory_key: ROS
  max_number_of_steps: -1
  ros_config:
    observation: camera
    visible_xterm: true
    step_rate_fps: 100
    ros_launch_config:
      random_seed: 123
      robot_name: turtlebot_real
      fsm_mode: TakeOverRun
      fsm: true
      control_mapping: true
      waypoint_indicator: false
      control_mapping_config: joystick
      world_name: default
      robot_display: true
      gazebo: False
    actor_configs:
      - name: joystick
        file: src/sim/ros/config/actor/joystick_turtlebot_real.yml
