output_path: adversarial_agents_ros/test
number_of_epochs: 400
episode_runner_config:
  number_of_episodes: 5
  train_every_n_steps: -1
architecture_config:
  log_std: -0.5
  architecture: adversarial_actor_critic_side_ways_ros
  device: cpu
  initialisation_type: orthogonal
  random_seed: 123
environment_config:
  factory_key: ROS
  normalize_rewards: true
  max_number_of_steps: 300
  ros_config:
    info:
      - frame
    observation: modified_state
    action_topic: python
    num_action_publishers: 2
    visible_xterm: false
    step_rate_fps: 100
    ros_launch_config:
      random_seed: 1273
      robot_name: double_drone_sim
      fsm_mode: TakeOverRun
      fsm: true
      control_mapping: true
      distance_tracking_fleeing_m: 3
      modified_state_publisher: true
      modified_state_publisher_mode: CombinedGlobalPoses
      modified_state_frame_visualizer: true
      waypoint_indicator: false
      control_mapping_config: python_adversarial
      world_name: tracking_y_axis
      gazebo: True
      starting_height: 1
    actor_configs:
      - name: altitude_control
data_saver_config:
  clear_buffer_before_episode: true
  store_on_ram_only: true
tensorboard: true
tb_render_every_n_epochs: 1
save_checkpoint_every_n: 5
trainer_config:
  criterion: MSELoss
  actor_learning_rate: 0.002
  critic_learning_rate: 0.001
  scheduler_config:
    number_of_epochs: 100
  gradient_clip_norm: -1
  optimizer: Adam
  data_loader_config:
    batch_size: 64
    random_seed: 5000
  device: cpu
  discount: 0.99
  factory_key: APPO
  gae_lambda: 0.95
  phi_key: gae
  entropy_coefficient: 0.01
  max_actor_training_iterations: 10
  max_critic_training_iterations: 10
  epsilon: 0.2
  use_kl_stop: false
  kl_target: 0.01
