teleop:
  piloting:
    type: topic
    message_type: "geometry_msgs/Twist"
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 3  # Right thumb stick (up/down)
        target: linear.x
        scale: 0.7
        offset: 0.0
      -
        axis: 0  # Left thumb stick (left/right)
        target: angular.z
        scale: 1.0
        offset: 0.0