specs:
  message: "
             Reading from the keyboard  and Publishing to Twist!
              ---------------------------
              Moving around:
                u (roll left)   i (up)         o (roll right)  p (take off)
                j (turn left)   k (straight)   l (turn right)  m (go)
                m (land)        ; (down)

               space (take over)
               e (emergency)"
  speed: 0.1
  turn: 0.5
  rate_fps: 10
  moveBindings:
    k:
      - 1
      - 0
      - 0
      - 0
      - 0
      - 0
    i:
      - 0
      - 0
      - 1
      - 0
      - 0
      - 0
    ';':
      - 0
      - 0
      - -1
      - 0
      - 0
      - 0
    u:
      - 0
      - 1
      - 0
      - 0
      - 0
      - 0
    o:
      - 0
      - -1
      - 0
      - 0
      - 0
      - 0
    j:
      - 0
      - 0
      - 0
      - 0
      - 0
      - 1
    l:
      - 0
      - 0
      - 0
      - 0
      - 0
      - -1
    J:
      - 1
      - 0
      - 0
      - 0
      - 0
      - 1
    L:
      - 1
      - 0
      - 0
      - 0
      - 0
      - -1
  topicBindings:
    m: '/fsm/go'
    ' ': '/fsm/overtake'
    r: '/fsm/reset'
    f: '/fsm/finish'
    p: '/tello/takeoff'
    ',': '/tello/land'
    e: '/tello/emergency'
    t: '/tello/flattrim'