specs:
  # Use on drone sim with slower measurement rate of 5Hz and control rate of 15Hz
  rate_fps: 15
  Kp_x: 1.0
  Ki_x: 0.3
  Kd_x: 0.3
  Kp_y: 1.0
  Ki_y: 0.3
  Kd_y: 0.3
  Kp_z: 1.0
  Ki_z: 0.3
  Kd_z: 0.
  K_theta: 1.0