specs:
  field_of_view: 100
  front_width: 40
  speed: 0.2
  noise:
    name: OUNoise
    args:
      dimension:
        - 6
        - 1
      seed: 1234
      mean: 0
      std: 0.2
      pullback: 0.3
  aggressiveness: 0
  collision_avoidance_weight: 0.2
  waypoint_following_weight: 0.8
  max_yaw_deviation_waypoint: 5
  rate_fps: 10