robot_type: 'quadrotor'
command_topic: '/tello/cmd_vel'
sensors:
  - 'forward_camera'
  - 'odometry'
forward_camera_topic: '/tello/image_raw'
forward_camera_type: 'Image'
forward_camera_stats:
  height: 128
  width: 128
  depth: 3
#  height: 200
#  width: 200
#  depth: 1
odometry_topic: '/tello/odom'
odometry_type: 'Odometry'
takeoff: '/tello/takeoff'
land: '/tello/land'
emergency: '/tello/emergency'
flattrim: '/tello/flattrim'