model_name: quadrotor_real
command_topic: /tello/cmd_vel
camera_sensor:
  topic: /tello/image_raw
  type: Image
  stats:
    height: 128
    width: 128
    depth: 3
#  height: 200
#  width: 200
#  depth: 1
position_sensor:
  topic: /tello/odom
  type: Odometry
takeoff: /tello/takeoff
land: /tello/land
emergency: /tello/emergency
flattrim: /tello/flattrim