# specify at which depth a collision takes is detected, note that sensor does not measure bellow 0.1m
collision_depth: 0.2
model_name: turtlebot3_burger
command_topic: /cmd_vel
camera_sensor:
  topic: /wa/camera/image_raw
  type: Image
  stats:
    height: 128
    width: 128
    depth: 3
depth_sensor:
  topic: /scan
  type: LaserScan
  stats:
    field_of_view: 120
    num_smooth_bins: 4
    max_depth: 4
    min_depth: 0.1
position_sensor:
  topic: /odom
  type: Odometry
